# Porta dell'app
server.port=8080

# ========== H2 DB ==========
spring.datasource.url=jdbc:h2:file:./data/hackhubdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# Mostra la console web di H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ========== JPA / HIBERNATE ==========
# Mostra le query SQL in console
spring.jpa.show-sql=true

# Format SQL leggibile
spring.jpa.properties.hibernate.format_sql=true
